import { Translation, Language } from '../types';

export const ADMIN_PASSWORD = 'maratha2407TGM'; // Simple password for demo
export const ADMIN_EMAILS = [
    'vedantdhawane2@gmail.com',
    'nareshratnaparkhi0211@gmail.com',
    'Aadityadhawane07@gmail.com'
];

export const SOCIAL_LINKS = {
    facebook: 'https://www.facebook.com/TGMM267',
    instagram: 'https://www.instagram.com/the_great_maratha_mitramandal/',
    youtube: 'https://www.youtube.com/@TheGreatMaratha700',
    whatsapp: 'https://whatsapp.com'
};

export const CONTACT_EMAIL = 'thegreatmararha6@gmail.com';

export const TRANSLATIONS: Record<Language, Translation> = {
    [Language.EN]: {
        title: "The Great Maratha",
        subtitle: "Uniting the community, preserving culture, and empowering the future.",
        home: "Home",
        about: "About Us",
        gallery: "Gallery",
        events: "Events",
        contact: "Contact",
        donate: "Donate",
        read_more: "Read More",
        student_portal: "Student Portal",
        student_list: "Student List",
        register_student: "Register New Student",
        search_student: "Search by name or roll number...",
        export_csv: "Export CSV",
        pending_requests: "Pending Applications",
        assign_roll_no: "Assign Roll No",
        approve: "Approve",
        reject: "Reject",
        no_students: "No students found.",
        student_photo: "Student Photo",
        roll_no: "Roll No",
        student_name: "Student Name",
        father_name: "Father's Name",
        dob: "Date of Birth",
        blood_group: "Blood Group",
        mobile_no: "Mobile No",
        aadhar_no: "Aadhar No",
        occupation: "Occupation",
        address: "Address",
        joined_date: "Joined Date",
        password_required: "Admin Access Required",
        enter_password: "Enter Admin Password",
        submit: "Submit",
        exit_admin: "Exit Admin",
        admin_access: "Admin Access",
        application_submitted: "Application Submitted!",
        waiting_approval: "Your application is pending approval by the admin.",
        latest_news: "Latest News: Celebrating 3 years of community service! | Next event: Annual Sports Day on Dec 25th.",
        hero_title: "Welcome to Our Community",
        hero_subtitle: "Building a brighter future together.",

        select_blood_group: "Select Blood Group",
        declaration: "I hereby declare that the information provided is true to the best of my knowledge.",
        admin_upload: "Post Update",
        write_message: "Write news or update description...",
        upload_media: "Upload Media",
        cancel: "Cancel",
        announcements: "Announcements",
        no_announcements: "No announcements yet.",
        posted_on: "Posted on",
        latest_updates: "Latest Updates",
        copyright: "All rights reserved.",
        group_highlights: "Group Highlights",
        see_more: "See More",
        see_less: "See Less",
        about_content: "The Great Maratha Mitra Mandal is a social service organization dedicated to working selflessly for the public. Founded by Naresh Ananta Ratnaparkhi, its headquarters are located in Barshitakali, District Akola, Maharashtra. The group is constantly working with the vision of social upliftment and keeping the spirit of patriotism alive. The core of the group's work is social service, spreading knowledge, preserving culture, and unity. Guided by the thoughts of Chhatrapati Shivaji Maharaj and Dr. Babasaheb Ambedkar, the group implements new initiatives for the society inspired by their teachings.\n\nKey activities of the group include cleanliness drives at public hospitals, police stations, government offices, and schools; providing free education to poor and needy children; and spreading knowledge among the general public. Inspired by the idea that 'everyone in society should get equal opportunities', the group performs the noble work of inculcating knowledge and values without charging any fees. Women, girls, and youth also actively participate, strengthening the sense of gender equality in society.\n\nThe Great Maratha Mitra Mandal is not limited to social service but also celebrates cultural and religious activities with equal enthusiasm. Every year, the group celebrates Chhatrapati Shivaji Maharaj Jayanti in a grand manner. It also encourages public participation in festivals like Holi, Sports Festivals, and Kawad Yatra. This helps maintain unity, brotherhood, and the true identity of our festivals in society.\n\nThe main objective of this group is to show the right direction to society, to teach everyone the true meaning of 'Humanity', and to bring everyone together to serve the nation and religion. Teaching 'how to be a true human being' is the passionate mission of this group. That is why today, The Great Maratha Mitra Mandal has become an inspiration for society, and it will continue to work for the upliftment of society through even greater service and cultural work in the future.",
        address_details: "Chhatrapati Shivaji Maharaj Chowk, Barshitakali, District Akola, Maharashtra, India",
        contact_info: "Contact Info",
        follow_us: "Follow Us",
        share: "Share",
        copy_link: "Copy Link",
        copied: "Copied!",
        slogan: "Strength in Unity",
        stats_members: "Members",
        stats_years: "Years",
        stats_events: "Events",
        our_community: "Our Community And Group",
        group_gallery: "Group Gallery",
        menu: "Menu",
        caption_message: "Caption / Message",
        tap_to_upload: "Tap to Take Photo/Video or Upload",
        saving: "Saving...",
        invalid_password: "Invalid Password",
        admin_post: "Admin Post",
        check_status: "Check Status",
        check_application_status: "Check Application Status",
        enter_mobile_search: "Enter Mobile Number to Search",
        status_pending: "Status: Pending Approval",
        status_approved: "Status: Approved",
        your_roll_no: "Your Roll No",
        search: "Search",
        application_not_found: "No application found with this mobile number.",
        video_gallery: "Video Gallery",
        watch_video: "Watch Video",
        close_video: "Close Video",
        upload_file: "File Upload",
        youtube_link: "YouTube Link"
    },
    [Language.MR]: {
        title: "द ग्रेट मराठा",
        subtitle: "समाजाला एकत्र आणणे, संस्कृतीचे जतन करणे आणि भविष्याला सक्षम करणे.",
        home: "मुख्यपृष्ठ",
        about: "आमच्याबद्दल",
        gallery: "गॅलरी",
        events: "कार्यक्रम",
        contact: "संपर्क",
        donate: "देणगी",
        read_more: "अधिक वाचा",
        student_portal: "विद्यार्थी दालन",
        student_list: "विद्यार्थी यादी",
        register_student: "नवीन नोंदणी",
        search_student: "नाव किंवा रोल नंबर शोधा...",
        export_csv: "CSV डाउनलोड",
        pending_requests: "प्रलंबित अर्ज",
        assign_roll_no: "रोल नंबर द्या",
        approve: "मंजूर करा",
        reject: "नाकारणे",
        no_students: "कोणीही विद्यार्थी सापडले नाहीत.",
        student_photo: "विद्यार्थी फोटो",
        roll_no: "रोल नंबर",
        student_name: "विद्यार्थ्याचे नाव",
        father_name: "वडिलांचे नाव",
        dob: "जन्मतारीख",
        blood_group: "रक्तगट",
        mobile_no: "मोबाईल क्र.",
        aadhar_no: "आधार क्र.",
        occupation: "व्यवसाय",
        address: "पत्ता",
        joined_date: "सामील तारीख",
        password_required: "प्रशासक प्रवेश आवश्यक",
        enter_password: "पासवर्ड प्रविष्ट करा",
        submit: "सादर करा",
        exit_admin: "प्रशासक बंद",
        admin_access: "प्रशासक प्रवेश",
        application_submitted: "अर्ज सादर केला!",
        waiting_approval: "तुमचा अर्ज प्रशासकाच्या मंजुरीच्या प्रतीक्षेत आहे.",
        latest_news: "ताज्या बातम्या: समाजसेवेची ३ वर्षे साजरी करत आहोत! | पुढील कार्यक्रम: २५ डिसेंबर रोजी वार्षिक क्रीडा दिवस.",
        hero_title: "आमच्या परिवारात स्वागत आहे",
        hero_subtitle: "एक उज्ज्वल भविष्य घडवूया.",

        select_blood_group: "रक्तगट निवडा",
        declaration: "मी याद्वारे घोषित करतो/करते की दिलेली माहिती माझ्या माहितीनुसार सत्य आहे.",
        admin_upload: "अपडेट पोस्ट करा",
        write_message: "बातम्या किंवा अपडेट लिहा...",
        upload_media: "मिडिया अपलोड करा",
        cancel: "रद्द करा",
        announcements: "घोषणा",
        no_announcements: "कोणतीही घोषणा नाही.",
        posted_on: "पोस्ट केले",
        latest_updates: "ताज्या घडामोडी",
        copyright: "सर्व हक्क राखीव.",
        group_highlights: "गट ठळक वैशिष्ट्ये",
        see_more: "अधिक पहा",
        see_less: "कमी पहा",
        about_content: "द ग्रेट मराठा मित्र मंडळ ही एक सामाजिक कार्याला वाहून घेतलेली संस्था आहे जी समाजातील जनतेसाठी निस्वार्थीपणे कार्य करते. या मंडळाची स्थापना नरेश अनंता रत्नपारखी यांनी केली असून, याचे मुख्य केंद्र बारशीटाकळी, जिल्हा अकोला, महाराष्ट्र येथे आहे. समाज उत्थान करण्याचा आणि राष्ट्रप्रेम जागृत ठेवण्याचा ध्यास घेऊन हे मंडळ सतत कार्यरत आहे. मंडळाच्या कार्याचा मुख्य गाभा म्हणजे सामाजिक सेवा, ज्ञानप्रसार, संस्कृती संवर्धन आणि एकता. हे मंडळ छत्रपती शिवाजी महाराज आणि डॉ. बाबासाहेब आंबेडकर यांच्या विचारांवर चालते आणि त्यांच्या शिकवणींमधून प्रेरणा घेऊन समाजासाठी सतत नवीन उपक्रम राबवते.\n\nया मंडळाने केलेल्या कार्यामध्ये सार्वजनिक रुग्णालये, पोलीस ठाणी, शासकीय कार्यालये, शाळा अशा अनेक ठिकाणांची स्वच्छता करणे, गरीब व गरजू मुलांना विनामूल्य शिक्षण देणे, तसेच सर्वसामान्य लोकांमध्ये ज्ञानाचा प्रसार करणे या उपक्रमांचा विशेष उल्लेख करता येईल. 'समाजातील प्रत्येकाला समान संधी मिळाली पाहिजे' या विचाराने प्रेरित होऊन हे मंडळ कोणतेही शुल्क न आकारता लोकांमध्ये ज्ञान व संस्कार रुजवण्याचे पवित्र कार्य करीत आहे. यामध्ये स्त्रिया, मुली आणि युवकांचाही सक्रिय सहभाग असतो, ज्यामुळे स्त्री-पुरुष समानतेची भावना समाजात बळकट होते.\n\nद ग्रेट मराठा मित्र मंडळ हे फक्त सामाजिक सेवेत मर्यादित न राहता, सांस्कृतिक आणि धार्मिक उपक्रमांनाही तेवढ्याच उत्साहाने साजरे करते. मंडळ दरवर्षी छत्रपती शिवाजी महाराज जयंती भव्यदिव्य स्वरूपात साजरी करते. तसेच होळी उत्सव, खेळ महोत्सव, कावड यात्रा अशा अनेक सांस्कृतिक व धार्मिक कार्यक्रमांत लोकांना सहभागी करून घेते. यामुळे समाजात एकोपा, बंधुभाव आणि सण-उत्सवांची खरी ओळख टिकून राहते.\n\nया मंडळाचा मुख्य उद्देश म्हणजे समाजाला योग्य दिशा दाखवणे, प्रत्येकाला खऱ्या अर्थाने ''मानवता'' शिकवणे आणि सर्वांना एकत्र आणून राष्ट्र व धर्माची सेवा करणे. ''खरा माणूस कसा व्हावा'' हे शिकवणे ही या मंडळाची ध्येयवेडी भूमिका आहे. त्यामुळेच आज महान मराठा मित्र मंडळ समाजासाठी एक प्रेरणास्थान ठरले आहे, जे भविष्यात आणखी मोठ्या प्रमाणात सेवा व संस्कृतीचे कार्य करून समाजाच्या उन्नतीसाठी कार्यरत राहील.",
        address_details: "छत्रपती शिवाजी महाराज चौक, बार्शीटाकळी, जिल्हा अकोला, महाराष्ट्र, भारत",
        contact_info: "संपर्क माहिती",
        follow_us: "आम्हाला फॉलो करा",
        share: "शेअर करा",
        copy_link: "लिंक कॉपी करा",
        copied: "कॉपी केले!",
        slogan: "एकतेत शक्ती आहे",
        stats_members: "सदस्य",
        stats_years: "वर्षे",
        stats_events: "कार्यक्रम",
        our_community: "आमचा समुदाय आणि गट",
        group_gallery: "ग्रुप गॅलरी",
        menu: "मेनू",
        caption_message: "कॅप्शन / संदेश",
        tap_to_upload: "फोटो/व्हिडिओ घेण्यासाठी किंवा अपलोड करण्यासाठी टॅप करा",
        saving: "जतन करत आहे...",
        invalid_password: "अवैध पासवर्ड",
        admin_post: "प्रशासक पोस्ट",
        check_status: "स्थिती तपासा",
        check_application_status: "अर्ज स्थिती तपासा",
        enter_mobile_search: "शोधण्यासाठी मोबाईल नंबर टाका",
        status_pending: "स्थिती: मंजुरीच्या प्रतीक्षेत",
        status_approved: "स्थिती: मंजूर",
        your_roll_no: "तुमचा रोल नंबर",
        search: "शोधा",
        application_not_found: "या मोबाईल नंबरसह कोणताही अर्ज सापडला नाही.",
        video_gallery: "व्हिडिओ गॅलरी",
        watch_video: "व्हिडिओ पहा",
        close_video: "व्हिडिओ बंद करा",
        upload_file: "फाइल अपलोड करा",
        youtube_link: "युट्यूब लिंक"
    }
};
